# Generated by Django 6.0.2 on 2026-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('design', 'Graphic Design'), ('development', 'Full Stack Development'), ('both', 'Design & Development')], max_length=20)),
                ('image', models.CharField(default='placeholder.jpg', max_length=500)),
                ('link', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField(default=80)),
            ],
        ),
    ]
