# Generated by Django 6.0.2 on 2026-03-10 06:22

import Portofolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portofolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('title', models.CharField(default='Graphics Designer & Full Stack Developer', max_length=200)),
                ('bio', models.TextField(default='Professional profile description')),
                ('profile_image', models.ImageField(default='profile/default.svg', upload_to=Portofolio.models.profile_image_path)),
                ('email', models.EmailField(default='your.email@example.com', max_length=254)),
                ('phone', models.CharField(default='+1 (234) 567-890', max_length=20)),
                ('location', models.CharField(default='Your City, Your Country', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/placeholder.jpg', upload_to=Portofolio.models.project_image_path),
        ),
    ]
